language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: IqKj9LQdIjjuULfSfqmuTsRmIj3PCeu6DPChbXJKj5hnqFm3u6nnRoQa8CAZHEBPTUN8lG1jqBtvRNF/VtuMbIpgTm7QqqwroSNP5YOZdFMJv0UeuricLnr6OS1TXNH0sBsyHVSgKqm8vVJFjZOX9Xbj/kLLRHviWLB4UC3C+hkorN3bi6ZseSu/eE7HCgkvSw/hLG6UPPmQGOmVHYJO4ZPEW1LxPHB5a17f+EY5Gdi6VjtNQR5KRxKzf1iOmvNclBMpoj84LOFJ7wZkOi25lznSIi0Dii+4Hld1fVv+hHmGP0gk5jXwXHpqBgnM3pw/+ZI+sslabTJH8rbb72Q4bdfeoeXfJT+0ek5TDJt++gpuCFRYiqVbMgyJwMYeN2faVh9O7GGHqtg01RNQ63tKXpM+ixYqHea0KM9SwVf4mjAQXXllzDoN/sRbY4tYaG82Uln31dGf7Y8kvPttrmfniUdd4FJzm4lUjaf3SfDIvH1ZsuZGsOkCn4tUGvDhZa1mfHt/nOdyNsGtq17tD8pOIqLbER7mTncmT6feKJGkj8nQkmHI9m/ZFAvoNiKi5w8NyjJMT94U43de6uwmvDNpyChua5htfCZrz95ZB4yk3tHbUK1P+5UrfeKrp+W7Ts9gfOrjhR5hjozDL3AaZkgkaqXdcvt3CKoNNgJn9rXM7x4=
  app: intense-eyrie-16911
  on:
    repo: rosaxny/blog-app-mongoose-challenge-solution
